#! /usr/bin/env python
import rospy
import tf
from geometry_msgs.msg import Twist
from sensor_msgs.msg import LaserScan
from nav_msgs.msg import Odometry
from math import pi, sqrt
import time

class Leader:
    def __init__(self):
        rospy.init_node('leader')
        self.vel_pub = rospy.Publisher("/ares1/cmd_vel", Twist, queue_size=1000)
        self.scan_sub = rospy.Subscriber("/ares1/scan", LaserScan, self.scan_callback)
        self.intensities = [0] * 27
        self.mul = 1
        self.rate =rospy.Rate(100000)

        while not rospy.is_shutdown():
            self.wander()
        rospy.spin()

    def scan_callback(self, msg):
        for i in range(27):
            self.intensities[i] = msg.intensities[i]
            self.mul = self.mul*self.intensities[i]
    
    def degree2radians(self, angle_in_degrees):
        return angle_in_degrees * pi/180.0
    
    def getDistance(self, x1, y1, x2, y2):
        return sqrt(pow(x1-x2,2) +pow(y1-y2, 2))


    def wander(self):
        samples = 27
        fov = 4.7123
        inc = 0.1745
        center = samples/2
        # obstacle in front
        if self.intensities[center-1] == 1 or self.intensities[center]==1 or self.intensities[center+1] ==1:
            for i in range(2, center):
                if self.intensities[center-i] == 0:
                    self.rotate(1.0, (i+1)*inc, clockwise=True)
                elif self.intensities[center+i] == 0:
                    self.rotate(1.0, (i+1)*inc, clockwise=False)
        else:
            self.move(0.5, 1.0, is_forward=True)

    
    def move(self, speed, distance, is_forward):
        vel_msg = Twist()
        if is_forward:
            vel_msg.linear.x = abs(speed)
        else:
            vel_msg.linear.x = -abs(speed)
        
        vel_msg.linear.y = 0
        vel_msg.linear.z = 0

        vel_msg.angular.x = 0
        vel_msg.angular.y = 0
        vel_msg.angular.z = 0

        t0 = time.time()
        current_distance = 0
        rate = rospy.Rate(100)
        while current_distance < distance:
            self.vel_pub.publish(vel_msg)
            t1 = time.time()
            current_distance = speed*(t1-t0)
            # rospy.spin()
            rate.sleep()
        
        vel_msg.linear.x = 0
        # self.vel_pub.publish(vel_msg)

    def rotate(self, angular_speed, relative_angle, clockwise):
        vel_msg = Twist()
        vel_msg.linear.x = 0
        vel_msg.linear.y = 0
        vel_msg.linear.z = 0

        vel_msg.angular.x = 0
        vel_msg.angular.y = 0

        if clockwise:
            vel_msg.angular.z = -abs(angular_speed)
        else:
            vel_msg.angular.z = abs(angular_speed)

        t0 = time.time()
        current_angle = 0
        rate =rospy.Rate(1000)
        while current_angle < relative_angle:
            self.vel_pub.publish(vel_msg)
            t1 = time.time()
            current_angle = angular_speed*(t1 - t0)
            rospy.spin()
            rate.sleep()
        vel_msg.angular.z = 0
        self.vel_pub.publish(vel_msg)


if __name__ == "__main__":
    leader = Leader()
    pass